version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      .env
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./init-rabbitmq.sh:/docker-entrypoint-init.d/init-rabbitmq.sh

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      target: backend
    container_name: app
    env_file:
      .env
    depends_on:
      - postgres
      - rabbitmq
      - redis
  nginx:
    build:
      context: .
      target: server
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - web

  consumidor:
    build:
      context: .
      target: backend
    container_name: consumidor
    env_file:
      .env
    command: celery -A lote_suinos worker --loglevel=info
    depends_on:
      - web

volumes:
  rabbitmq_data:
    driver: local
  redis_data:
    driver: local
  postgres_data:
    driver: local